spring.application.name=budgeting

# ---------- Spring AI / OpenAI ----------
#spring.ai.openai.api-key=${OPENAI_API_KEY:chave-nao-configurada}
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.model=gpt-4o-mini

spring.ai.openai.chat.temperature=0.2 
# Extrações de dados funanceiros não pode ser criativa 

# ---------- Banco (H2 em memoria, por enquanto) ----------
spring.datasource.url=jdbc:h2:mem:budgeting
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# ---------- Upload de audio (etapa 5) ----------
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB


# Imprime o payload que sai e volta da OpenAI. Ver as mensagens system e user sendo montadas
#logging.level.org.springframework.ai=DEBUG

logging.level.org.springframework.ai=INFO




# ---------- Transcricao (STT) ----------
spring.ai.openai.audio.transcription.model=whisper-1
spring.ai.openai.audio.transcription.language=pt
spring.ai.openai.audio.transcription.temperature=0
spring.ai.openai.audio.transcription.prompt=Registro de gastos pessoais em reais. Termos comuns: Starbucks, mercado, combustivel, almoco, farmacia, Uber.




# ---------- Sintese de voz (TTS) ----------
spring.ai.openai.audio.speech.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.voice=nova
spring.ai.openai.audio.speech.response-format=mp3
spring.ai.openai.audio.speech.speed=1.0




spring.jpa.open-in-view=false 



# ---------- Documentacao da API ----------
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true